#!/bin/bash

docker build \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
  --build-arg VERSION=1.3 \
  -f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
